version: '3.8'
# No database service needed — app is fully stateless
services:
  api:
    build: ./BirdsAtlas.API
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build: ./birds-atlas-ui
    ports:
      - "4200:80"
    depends_on:
      - api
